### ISSUE TITLE
Sample Android app crashes on Plans screen

### ISSUE THREAD

**Issue by matt-ramotar** [dropbox/componentbox#8]
```
E/AndroidRuntime: FATAL EXCEPTION: Zipline
    Process: com.dropbox.componentbox.discovery, PID: 3219
    app.cash.zipline.QuickJsException: Only KClass supported as classifier, got C
        at JavaScript.vc(zipline)
        at JavaScript.ph(zipline)
        at JavaScript.b$(zipline)
        at JavaScript.kk(zipline)
        at JavaScript.hk(zipline)
        at JavaScript.<anonymous>(zipline)
        at JavaScript.kk(zipline)
        at JavaScript.hk(zipline)
        at JavaScript.AC(zipline)
        at JavaScript.<anonymous>(zipline)
        at JavaScript.<anonymous>(zipline)
        at JavaScript.<anonymous>(zipline)
        at JavaScript.<anonymous>(zipline)
        at JavaScript.tj(zipline)
        at JavaScript.<anonymous>(zipline)
        at JavaScript.<anonymous>(zipline)
        at JavaScript.<eval>(?)
        at app.cash.zipline.QuickJs.evaluate(Native Method)
        at app.cash.zipline.QuickJs.evaluate(QuickJs.kt:110)
        at app.cash.zipline.QuickJs.evaluate$default(QuickJs.kt:109)
        at com.dropbox.componentbox.discovery.zipline.ComponentBoxZipline$produceModelsIn$job$1.invokeSuspend(ComponentBoxZipline.kt:41)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

**Comment by matt-ramotar** [comment]
[js](https://github.com/dropbox/componentbox/files/8193704/componentbox_8.txt)

**Comment by matt-ramotar** [comment]
https://github.com/cashapp/zipline/blob/57fb4b617f768aeab87d21a799fdec9d792d2856/zipline-kotlin-plugin/tests/src/test/kotlin/app/cash/zipline/kotlin/ZiplineKotlinPluginTest.kt#L181-L217

**Comment by matt-ramotar** [comment]
https://github.com/cashapp/zipline/issues/420
